services:
  cloudflaredcali:
    image: cloudflare/cloudflared:latest
    container_name: cloudflaredcali
    restart: always
    networks:
      - internal
    command: tunnel --no-autoupdate run --token eyJhIjoiZWQ2NmE1NDZlYWVhMWNlMDBlYjE2YmI1Yzc1NmFkY2EiLCJ0IjoiZmRhOGJiYTEtMDU4MC00OWQzLTllZjAtZmZkYmNmNTUwMGZlIiwicyI6Ik56ZGpObU16WlRVdE9URmhaQzAwWmpVNExXSXlOakF0Tm1FM01qTmlPRGMwTm1VdyJ9
  appcali:
    image: appcali
    hostname: appcali
    restart: always
    container_name: appcali
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    environment:
      PORT: 3000
      MONGODB_URI: mongodb+srv://cachorro_cami:Tengo1amo@cluster0.ffbyjzl.mongodb.net/?retryWrites=true&w=majority
      NODE_ENV: production
    ports:
      - 6666:3000
    expose:
      - 3000
    networks:
      - internal

networks:
  internal:
    external: true
    name: internal
