declare const styles: {
  readonly black: string;
  readonly ctas: string;
  readonly footer: string;
  readonly img: string;
  readonly main: string;
  readonly page: string;
  readonly parallax: string;
  readonly parallaxImage1: string;
  readonly parallaxImage2: string;
  readonly parallaxImage3: string;
  readonly primary: string;
  readonly scrollButton: string;
  readonly secondary: string;
  readonly subtitleParagraph: string;
  readonly textParagraph: string;
  readonly thumbnails: string;
  readonly title: string;
  readonly titleParagraph: string;
};
export = styles;
