import type { Metadata, Viewport } from 'next';
import { Geist_Mono, Josefin_Sans, Playfair_Display, PT_Serif_Caption, Radio_Canada, Raleway } from 'next/font/google';
import '#@/styles/globals.css';
import { NavBar } from '#@/components/navbar';
import { ReactNode } from 'react';
import { NavigationContextProvider } from './context/navigation-context';
import 'material-symbols';
import styles from '#@/styles/layout.module.css';

const prefix = process.env.NODE_ENV === 'production'
  ? 'app'
  : 'beta';

const hostname = `https://${ prefix }.suarez-ramirez.com`;

export const metadata: Metadata = {
  metadataBase: new URL(
    hostname
  ),
  title          : 'proyecto cali',
  description    : 'Generated by create next app',
  generator      : 'proyecto cali',
  applicationName: 'proyecto cali',
  referrer       : 'origin-when-cross-origin',
  keywords       : [
    'Next.js',
    'React',
    'JavaScript'
  ],
  authors: [
    {
      name: 'Camilo Suarez',
    },
    {
      name: 'Cachorro Cami',
      url : hostname,
    },
  ],

  creator        : 'Cachorro Cami',
  publisher      : 'CachorroC',
  alternates     : {},
  formatDetection: {
    email    : false,
    address  : false,
    telephone: false,
  },
  appleWebApp: {
    capable       : true,
    title         : 'proyecto cali',
    statusBarStyle: 'black-translucent',
    startupImage  : [
      'src/app/logo.svg',
      {
        url  : '/logo.svg',
        media: '(device-width: 768px) and (device-height: 1024px)',
      },
    ],
  },
  appLinks: {
    web: {
      url            : '/',
      should_fallback: true,
    },
  },
};

export const viewport: Viewport = {
  width            : 'device-width',
  initialScale     : 1,
  maximumScale     : 1,
  colorScheme      : 'light dark',
  interactiveWidget: 'resizes-content',
  themeColor       : [
    {
      media: '(prefers-color-scheme: light)',
      color: '#5C6BC0',
    },
    {
      media: '(prefers-color-scheme: dark)',
      color: '#1A237E',
    },
  ],
};

const josefinSans = Josefin_Sans(
  {
    variable: '--font-josefin-sans',
    subsets : [
      'latin'
    ],
  }
);

const geistMono = Geist_Mono(
  {
    variable: '--font-geist-mono',
    subsets : [
      'latin'
    ],
  }
);

const playDisp = Playfair_Display(
  {
    subsets: [
      'latin-ext',
      'latin'
    ],
    preload : true,
    variable: '--play-display',
    weight  : 'variable',
  }
);

const ptserif = PT_Serif_Caption(
  {
    subsets: [
      'latin'
    ],
    display : 'auto',
    preload : false,
    variable: '--ptserif',
    weight  : '400',
  }
);

const josefina = Josefin_Sans(
  {
    subsets: [
      'latin'
    ],
    preload : false,
    variable: '--josefa',
    weight  : 'variable',
  }
);

const radio = Radio_Canada(
  {
    subsets: [
      'latin-ext'
    ],
    preload : false,
    variable: '--radio',
  }
);

const raleway = Raleway(
  {
    subsets: [
      'latin'
    ],
    preload : true,
    variable: '--raleway',
  }
);

export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: ReactNode;
  }>
) {
  return (
    <html lang="en">
      <body
        className={`${ josefinSans.className } ${ geistMono.variable } ${ playDisp.variable }  ${ raleway.variable } ${ radio.variable } ${ ptserif.variable }[ color-scheme: light dark ]`}
      >
        <NavigationContextProvider>
          <div className={styles.container}>
            <NavBar />
            {children}
          </div>
        </NavigationContextProvider>
      </body>
    </html>
  );
}
